stages:
  - initial-build
  - post-build

variables:
  GIT_CLEAN_FLAGS: none

android-armv7:
  tags:
    - android
    - armv7
  stage: initial-build
  script:
    - . $HOME/.cargo/env
    - export PATH=$PATH:/home/ci_worker/arch-ndk/armv7/android-ndk/bin
    - cargo build --features native --target=armv7-linux-androideabi --release --lib
  artifacts:
    paths:
      - target/armv7-linux-androideabi/release/libmm2.a

android-aarch64:
  tags:
    - android
    - aarch64
  stage: initial-build
  script:
    - . $HOME/.cargo/env
    - export PATH=$PATH:/home/ci_worker/arch-ndk/aarch64/android-ndk/bin
    - cargo build --features native --target=aarch64-linux-android --release --lib
  artifacts:
    paths:
      - target/aarch64-linux-android/release/libmm2.a

android-x86_64:
  tags:
    - android
    - x86_64
  stage: initial-build
  script:
    - . $HOME/.cargo/env
    - export PATH=$PATH:/home/ci_worker/arch-ndk/x86_64/android-ndk/bin
    - cargo build --features native --target=x86_64-linux-android --release --lib
  artifacts:
    paths:
      - target/x86_64-linux-android/release/libmm2.a

android-i686:
  tags:
    - android
    - i686
  stage: initial-build
  script:
    - . $HOME/.cargo/env
    - export PATH=$PATH:/home/ci_worker/arch-ndk/i686/android-ndk/bin
    - cargo build --features native --target=i686-linux-android --release --lib
  artifacts:
    paths:
      - target/i686-linux-android/release/libmm2.a

macos-aarch64:
  tags:
    - mac
    - aarch64
  stage: post-build
  needs:
    - job: macos-build
  script:
    - cp /Users/administrator/GitLab/archive/aarch64/libmm2.a .
  artifacts:
    paths:
      - libmm2.a

macos-x86_64:
  tags:
    - mac
    - x86_64
  stage: post-build
  needs:
    - job: macos-build
  script:
    - cp /Users/administrator/GitLab/archive/x86_64/libmm2.a .
  artifacts:
    paths:
      - libmm2.a

macos-universal:
  tags:
    - mac
    - universal
  stage: post-build
  needs:
    - job: macos-build
  script:
    - cp /Users/administrator/GitLab/archive/universal/libmm2.a .
  artifacts:
    paths:
      - libmm2.a

macos-build:
  tags:
    - mac
    - universal
  stage: initial-build
  script:
    - cargo lipo --features native --targets x86_64-apple-ios,aarch64-apple-ios --release
    - cp target/universal/release/libmm2.a /Users/administrator/GitLab/archive/universal/libmm2.a
    - cp target/x86_64-apple-ios/release/libmm2.a /Users/administrator/GitLab/archive/x86_64/libmm2.a
    - cp target/aarch64-apple-ios/release/libmm2.a /Users/administrator/GitLab/archive/aarch64/libmm2.a
