stages:
  - initial-build
  - post-build

variables:
  GIT_CLEAN_FLAGS: none

android-armv7:
  tags:
    - android
    - armv7
  stage: initial-build
  script:
    - . $HOME/.cargo/env
    - export PATH=$PATH:/home/azureagent/android-ndk/arch-ndk/armv7/android-ndk/bin
    - CC_armv7_linux_androideabi=armv7a-linux-androideabi21-clang CARGO_TARGET_ARMV7_LINUX_ANDROIDEABI_LINKER=armv7a-linux-androideabi21-clang cargo build --features native --target=armv7-linux-androideabi --release --lib
  artifacts:
    paths:
      - target/armv7-linux-androideabi/release/libmm2.a

android-aarch64:
  tags:
    - android
    - aarch64
  stage: initial-build
  script:
    - . $HOME/.cargo/env
    - export PATH=$PATH:/home/azureagent/android-ndk/arch-ndk/aarch64/android-ndk/bin/
    - CC_aarch64_linux_android=aarch64-linux-android21-clang CARGO_TARGET_AARCH64_LINUX_ANDROID_LINKER=aarch64-linux-android21-clang cargo build --features native --target=aarch64-linux-android --release --lib
  artifacts:
    paths:
      - target/aarch64-linux-android/release/libmm2.a

android-x86_64:
  tags:
    - android
    - x86_64
  stage: initial-build
  script:
    - . $HOME/.cargo/env
    - export PATH=$PATH:/home/azureagent/android-ndk/arch-ndk/x86_64/android-ndk/bin
    - CARGO_TARGET_X86_64_LINUX_ANDROID_LINKER=x86_64-linux-android21-clang CC_x86_64_linux_android=x86_64-linux-android21-clang cargo build --features native --target=x86_64-linux-android --release --lib
  artifacts:
    paths:
      - target/x86_64-linux-android/release/libmm2.a

android-i686:
  tags:
    - android
    - i686
  stage: initial-build
  script:
    - . $HOME/.cargo/env
    - export PATH=$PATH:/home/azureagent/android-ndk/arch-ndk/i686/android-ndk/bin
    - CARGO_TARGET_I686_LINUX_ANDROID_LINKER=i686-linux-android21-clang CC_i686_linux_android=i686-linux-android21-clang cargo build --features native --target=i686-linux-android --release --lib
  artifacts:
    paths:
      - target/i686-linux-android/release/libmm2.a

macos-aarch64:
  tags:
    - mac
    - aarch64
  stage: post-build
  needs:
    - job: macos-build
  script:
    - cp /Users/hetzner/GitLab/archive/aarch64/libmm2.a .
  artifacts:
    paths:
      - libmm2.a

#macos-x86_64:
#  tags:
#    - mac
#    - x86_64
#  stage: post-build
#  needs:
#    - job: macos-build
#  script:
#    - cp /Users/administrator/GitLab/archive/x86_64/libmm2.a .
#  artifacts:
#    paths:
#      - libmm2.a

#macos-universal:
#  tags:
#    - mac
#    - universal
#  stage: post-build
#  needs:
#    - job: macos-build
#  script:
#    - cp /Users/administrator/GitLab/archive/universal/libmm2.a .
#  artifacts:
#    paths:
#      - libmm2.a

macos-build:
  tags:
    - mac
    - universal
  stage: initial-build
  script:
#    - cargo lipo --features native --targets x86_64-apple-ios,aarch64-apple-ios --release
# TMP disable universal builds until x86_64 build is fixed on server
    - IPHONEOS_DEPLOYMENT_TARGET=9.0 cargo build --target aarch64-apple-ios --release --lib
    - cp target/aarch64-apple-ios/release/libmm2.a /Users/hetzner/GitLab/archive/aarch64/libmm2.a
#    - cp target/universal/release/libmm2.a /Users/hetzner/GitLab/archive/universal/libmm2.a
#    - cp target/x86_64-apple-ios/release/libmm2.a /Users/hetzner/GitLab/archive/x86_64/libmm2.a
