# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

variables:
  - group: passphrases

trigger:
  branches:
    include:
      - refs/heads/*
  paths:
    exclude:
      - docs/*
      - README.md
      - mm2src/README.md
      - etomic_build/*
      - iguana/Readme.md
      - .gitignore

pr: # https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=schema%2Cparameter-schema#pr-trigger
  drafts: false

stages:
  - stage: Lint
    displayName: Formatting, Clippy, and other checks
    jobs:
      - template: azure-pipelines-lint-stage-job.yml  # Template reference
        parameters:
          name: 'MM2_Lint_Linux'
          os: 'Linux'

      - template: azure-pipelines-lint-stage-job.yml  # Template reference
        parameters:
          name: 'MM2_Lint_MacOS'
          os: 'Darwin'

      - template: azure-pipelines-lint-stage-job.yml  # Template reference
        parameters:
          name: 'MM2_Lint_Win'
          os: 'Windows_NT'

  - stage: WASM
    displayName: WASM build and test
    condition: succeeded('Lint')
    jobs:
      - template: azure-pipelines-wasm-stage-job.yml  # Template reference
        parameters:
          name: 'MM2_WASM_Linux'
          os: 'Linux'
          bob_passphrase: 'BOB_PASSPHRASE_LINUX'
          bob_userpass: 'BOB_USERPASS_LINUX'
          alice_passphrase: 'ALICE_PASSPHRASE_LINUX'
          alice_userpass: 'ALICE_USERPASS_LINUX'
          telegram_api_key: 'TELEGRAM_API_KEY'

  - stage: Build
    displayName: Build and test Debug
    condition: succeeded('WASM')
    jobs:
      - template: azure-pipelines-build-stage-job.yml  # Template reference
        parameters:
          name: 'MM2_Build_Linux'
          os: 'Linux'
          bob_passphrase: 'BOB_PASSPHRASE_LINUX'
          bob_userpass: 'BOB_USERPASS_LINUX'
          alice_passphrase: 'ALICE_PASSPHRASE_LINUX'
          alice_userpass: 'ALICE_USERPASS_LINUX'
          telegram_api_key: 'TELEGRAM_API_KEY'

      - template: azure-pipelines-build-stage-job.yml  # Template reference
        parameters:
          name: 'MM2_Build_MacOS'
          os: 'Darwin'
          bob_passphrase: 'BOB_PASSPHRASE_MAC'
          bob_userpass: 'BOB_USERPASS_MAC'
          alice_passphrase: 'ALICE_PASSPHRASE_MAC'
          alice_userpass: 'ALICE_USERPASS_MAC'
          telegram_api_key: 'TELEGRAM_API_KEY'

      - template: azure-pipelines-build-stage-job.yml  # Template reference
        parameters:
          name: 'MM2_Build_Windows'
          os: 'Windows_NT'
          bob_passphrase: 'BOB_PASSPHRASE_WIN'
          bob_userpass: 'BOB_USERPASS_WIN'
          alice_passphrase: 'ALICE_PASSPHRASE_WIN'
          alice_userpass: 'ALICE_USERPASS_WIN'
          telegram_api_key: 'TELEGRAM_API_KEY'
