[build.env]
passthrough = [
  "NDK_HOME",
  "RUST_BACKTRACE"
]

[target.armv7-linux-androideabi]
image = "armv7-linux-androideabi-aga"

[target.aarch64-linux-android]
image = "aarch64-linux-android-aga"
