[package]
name = "common"
version = "0.1.0"
links = "marketmaker-mainnet-lib"
edition = "2018"

[lib]
name = "common"
path = "common.rs"
doctest = false

[dependencies]
arrayref = "0.3"
async-std = { version = "1.5", features = ["unstable"] }
atomic = { version = "^0.4.6", features = ["nightly"] }
async-trait = "0.1"
backtrace = "0.3"
base64 = "0.10.0"
bigdecimal = { version = "0.1", features = ["serde"] }
bitcrypto = { git = "https://github.com/artemii235/parity-bitcoin.git" }
bytes = "0.4"
crossbeam = "0.7"
findshlibs = "0.5"
fomat-macros = "0.2"
futures01 = { version = "0.1", package = "futures" }
futures = { version = "0.3", package = "futures", features = ["compat", "async-await"] }
futures-cpupool = "0.1"
gstuff = { version = "0.6", features = ["nightly"] }
hex = "0.3.2"
http = "0.2"
http-body = "0.1"
itertools = "0.8"
keys = { git = "https://github.com/artemii235/parity-bitcoin.git" }
lazy_static = "1.2"
log = "0.4.8"
num-bigint = { version = "0.2", features = ["serde", "std"] }
num-rational = { version = "0.2", features = ["serde", "bigint", "bigint-std"] }
num-traits = "0.2"
parking_lot = { version = "0.11", features = ["nightly"] }
parking_lot_core = { version = "0.6", features = ["nightly"] }
paste = "1.0"
primitives = { git = "https://github.com/artemii235/parity-bitcoin.git" }
rand = { version = "0.7", features = ["std", "small_rng"] }
regex = "1"
serde = "1"
serde_bytes = "0.11"
serde_derive = "1"
serde_json = { version = "1.0", features = ["raw_value", "preserve_order"] }
serde_repr = "0.1.6"
term = "0.5"
uuid = { version = "0.7", features = ["serde", "v4"] }
winapi = "0.3"

[target.'cfg(target_arch = "wasm32")'.dependencies]
chrono = { version = "0.4", features = ["wasmbind"] }
js-sys = "0.3.27"
serde_bencode = "0.2"
wasm-bindgen = { version = "0.2.50", features = ["serde-serialize", "nightly"] }
wasm-bindgen-futures = "0.4.21"
web-sys = { version = "0.3.4", features = ["console"] }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
chrono = "0.4"
hdrhistogram = { version = "7.0", default-features = false, features = ["sync"] }
hyper = { version = "0.13" }
# using webpki-tokio to avoid rejecting valid certificates
# got "invalid certificate: UnknownIssuer" for https://ropsten.infura.io on iOS using default-features
hyper-rustls = { version = "0.20", default-features = false, features = ["webpki-tokio"] }
libc = { version = "0.2" }
log4rs = { version = "0.13" }
metrics = { version = "0.12" }
metrics-runtime = { version = "0.13", default-features = false, features = ["metrics-observer-prometheus"] }
metrics-core = { version = "0.5" }
metrics-util = { version = "0.3" }
rusqlite = { version = "0.24.2", features = ["bundled"] }
tokio = { version = "0.2.22", features = ["io-util", "rt-threaded", "stream", "tcp"] }

[build-dependencies]
cc = "1.0"
fomat-macros = "0.3"
gstuff = { version = "0.6", features = ["nightly", "term"] }
