[package]
name = "common"
version = "0.1.0"
links = "marketmaker-mainnet-lib"
edition = "2018"

[features]
native = [
  "hyper", "hyper-rustls", "libc", "ring", "tokio-core"
]

[lib]
name = "common"
path = "common.rs"
doctest = false

[dependencies]
arrayref = "0.3"
backtrace = "0.3"
# Using the `chrono` because the `time` formatting has serious limits, like the lack of subsecond support, IIRC.
chrono = "0.4"
crossbeam = "0.6"
fomat-macros = "0.2"
futures = "0.1"
gstuff = "0.5"
hashbrown = {version = "0.1.8", features = ["serde", "nightly"]}
hex = "0.3.2"
http = "0.1"
http-body = "0.1"
keys = { git = "https://github.com/artemii235/parity-bitcoin.git" }
lazy_static = "1.3"
libc = { version = "0.2", optional = true }
hyper = { version = "0.12", optional = true }
hyper-rustls = { version = "0.16", optional = true }
primitives = { git = "https://github.com/artemii235/parity-bitcoin.git" }
rand = { version = "0.7", features = ["std", "small_rng"] }
regex = "1"
# To build `ring` on Windows we might need `perl` and `yasm` in the PATH
# (though I haven't checked this in a while).
# Download http://www.tortall.net/projects/yasm/releases/yasm-1.3.0-win64.exe and rename to `yasm.exe`.
ring = { version = "0.14", optional = true }
serde = "1"
serde_derive = "1"
serde_json = "1"
term = "0.5"
tokio-core = { version = "0.1", optional = true }
unwrap = "1.2"

[build-dependencies]
bindgen = "0.43"
bzip2 = "0.3"
cc = "1.0"
fomat-macros = "0.3"
futures = "0.1"
futures-cpupool = "0.1"
glob = "0.3"
gstuff = "0.5"
hyper = "0.12"
hyper-rustls = "0.16"
itertools = "0.8"
lazy_static = "1.3"
libflate = "0.1"
num_cpus = "1.10"
regex = "1"
tar = "0.4"
unwrap = "1.2.1"
winapi = "0.3"
