[package]
name = "serialization_derive"
version = "0.1.0"
authors = ["debris <marek.kotewicz@gmail.com>"]

[lib]
name = "serialization_derive"
proc-macro = true

[dependencies]
syn = "0.11.11"
quote = "1.0.20"

[dev-dependencies]
serialization = { path = "../serialization" }
