[package]
name = "lightning-persister"
version = "0.0.106"
edition = "2018"
authors = ["Valentine Wallace", "Matt Corallo"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/lightningdevkit/rust-lightning/"
description = """
Utilities to manage Rust-Lightning channel data persistence and retrieval.
"""

[dependencies]
async-trait = "0.1"
bitcoin = "0.27.1"
common = { path = "../../common" }
mm2_io = { path = "../../mm2_io" }
db_common = { path = "../../db_common" }
derive_more = "0.99"
hex = "0.4.2"
lightning = { git = "https://github.com/shamardy/rust-lightning", branch = "0.0.106" }
libc = "0.2"
parking_lot = { version = "0.12.0", features = ["nightly"] }
secp256k1 = { version = "0.20" }
serde = "1.0"
serde_json = "1.0"

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3", features = ["winbase"] }

[dev-dependencies]
lightning = { git = "https://github.com/shamardy/rust-lightning", branch = "0.0.106", features = ["_test_utils"] }
rand = { version = "0.7", features = ["std", "small_rng"] }