[package]
name = "lightning-persister"
version = "0.0.104"
edition = "2018"
authors = ["Valentine Wallace", "Matt Corallo"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/lightningdevkit/rust-lightning/"
description = """
Utilities to manage Rust-Lightning channel data persistence and retrieval.
"""

[dependencies]
async-trait = "0.1"
bitcoin = "0.27.1"
common = { path = "../../common" }
lightning = "0.0.104"
libc = "0.2"
parking_lot = { version = "0.12.0", features = ["nightly"] }
secp256k1 = { version = "0.20" }
serde_json = "1.0"

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3", features = ["winbase"] }

[dev-dependencies]
lightning = { version = "0.0.104", features = ["_test_utils"] }