name: 'Set up cargo cache'
description: 'Sets up the cargo cache for the workflow'
runs:
  using: 'composite'
  steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: Set up cargo cache
      uses: Swatinem/rust-cache@v2

    - name: Configure sccache
      shell: bash
      run: | 
          echo "RUSTC_WRAPPER=sccache" >> $GITHUB_ENV
          echo "SCCACHE_GHA_ENABLED=true" >> $GITHUB_ENV

    - name: Set up sccache-cache
      uses: mozilla-actions/sccache-action@v0.0.7
