name: 'Set up build cache'
description: 'Sets up caching for KDF builds'
runs:
  using: 'composite'
  steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up rust-cache
      uses: Swatinem/rust-cache@v2
