[package]
name = "spv_validation"
version = "0.1.0"
authors = ["Roman Sztergbaum <rmscastle@gmail.com>"]

[dependencies]
bitcoin-spv = "5.0.0"
chain = {path = "../chain"}
primitives = { path = "../primitives" }
serialization = { path = "../serialization" }
rustc-hex = "2"