[package]
name = "lightning-background-processor"
version = "0.0.106"
authors = ["Valentine Wallace <vwallace@protonmail.com>"]
license = "MIT OR Apache-2.0"
repository = "http://github.com/lightningdevkit/rust-lightning"
description = """
Utilities to perform required background tasks for Rust Lightning.
"""
edition = "2018"

[dependencies]
bitcoin = "0.27.1"
lightning = { git = "https://github.com/shamardy/rust-lightning", branch = "0.0.106", features = ["std"] }

[dev-dependencies]
db_common = { path = "../../db_common" }
lightning = { git = "https://github.com/shamardy/rust-lightning", branch = "0.0.106", features = ["_test_utils"] }
lightning-invoice = { git = "https://github.com/shamardy/rust-lightning", branch = "0.0.106" }
lightning-persister = { version = "0.0.106", path = "../lightning_persister" }
