[package]
name = "mm2_p2p"
version = "0.1.0"
edition = "2021"

[lib]
doctest = false

[dependencies]
async-trait = "0.1"
common = { path = "../common" }
derive_more = "0.99"
futures = { version = "0.3.1", package = "futures", features = ["compat", "async-await"] }
futures-rustls = { version = "0.21.1" }
hex = "0.4.2"
lazy_static = "1.4"
secp256k1 = { version = "0.20", features = ["rand"] }
log = "0.4"
rand = { package = "rand", version = "0.7", features = ["std", "wasm-bindgen"] }
regex = "1"
rmp-serde = "0.14.3"
serde = { version = "1.0", features = ["derive"] }
serde_bytes = "0.11.5"
sha2 = "0.9"
syn = "2.0.18"
void = "1.0"
pin-project = "1.1.0"
futures-ticker = "0.0.3"
libp2p-identity = "0.1.2"
tracing = "0.1.37"
fnv = "1.0.7"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
instant = "0.1.12"
tokio = { version = "1.20", features = ["rt-multi-thread", "macros"] }
libp2p = { git = "https://github.com/libp2p/rust-libp2p.git", branch = "master", default-features = false, features = ["async-std", "dns", "identify", "floodsub", "gossipsub", "noise", "ping", "request-response", "secp256k1", "tcp", "tokio", "websocket", "macros", "yamux"] }

[target.'cfg(target_arch = "wasm32")'.dependencies]
instant = { version = "0.1.12", features = ["wasm-bindgen"] }
libp2p = { git = "https://github.com/libp2p/rust-libp2p.git", branch = "master", default-features = false, features = ["async-std", "identify", "floodsub", "noise", "gossipsub", "ping", "request-response", "secp256k1", "wasm-ext", "wasm-ext-websocket", "macros", "yamux"] }
wasm-bindgen-futures = "0.4.21"
