name: ADEX linux build

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install Dependencies
      run: rustup install nightly-2022-02-01
    - run: rustup default nightly-2022-02-01
    - run: rustup component add rustfmt-preview
    - name: Build
      run: cargo build --v
    - name: Run tests
      run: cargo test --v

