name: Development builds
on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
 BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
 MANUAL_MM_VERSION: true

jobs:
  linux-x86-64:
    timeout-minutes: 30
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v3
    - name: Install toolchain
      run: |
        rustup toolchain install nightly-2022-10-29 --no-self-update --profile=minimal
        rustup default nightly-2022-10-29

    - name: Calculate commit hash for PR commit
      if: github.event_name == 'pull_request'
      run: echo "COMMIT_HASH=$(git rev-parse --short=7 ${{ github.event.pull_request.head.sha }})" >> $GITHUB_ENV

    - name: Calculate commit hash for merge commit
      if: github.event_name != 'pull_request'
      run: echo "COMMIT_HASH=$(git rev-parse --short=7 HEAD)" >> $GITHUB_ENV

    - name: Build
      run: |
        rm -f ./MM_VERSION
        echo $COMMIT_HASH > ./MM_VERSION
        cargo build --bin mm2 --profile ci

    - name: Compress build output
      run: |
        NAME="mm2_$COMMIT_HASH-linux-x86-64.zip"
        zip $NAME target/ci/mm2 -j
        mkdir $BRANCH_NAME
        mv $NAME ./$BRANCH_NAME/

    - name: Upload output
      uses: garygrossgarten/github-action-scp@release
      with:
        host: ${{ secrets.FILE_SERVER_HOST }}
        username: ${{ secrets.FILE_SERVER_USERNAME }}
        port: ${{ secrets.FILE_SERVER_PORT }}
        privateKey: ${{ secrets.FILE_SERVER_KEY }}
        local: ${{ env.BRANCH_NAME }}
        remote: "/uploads/${{ env.BRANCH_NAME }}"

    - name: Login to dockerhub
      if: github.event_name != 'pull_request'
      run: docker login --username ${{ secrets.DOCKER_HUB_USERNAME }} --password ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}  docker.io

    - name: Build and push container image
      if: github.event_name != 'pull_request'
      run: |
        CONTAINER_TAG="dev-$COMMIT_HASH"
        docker build -t komodoofficial/atomicdexapi:"$CONTAINER_TAG" -t komodoofficial/atomicdexapi:dev-latest -f Dockerfile.dev-release .
        docker push komodoofficial/atomicdexapi:"$CONTAINER_TAG"
        docker push komodoofficial/atomicdexapi:dev-latest

  mac-x86-64:
    timeout-minutes: 30
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install toolchain
      run: |
        rustup toolchain install nightly-2022-10-29 --no-self-update --profile=minimal
        rustup default nightly-2022-10-29

    - name: Calculate commit hash for PR commit
      if: github.event_name == 'pull_request'
      run: echo "COMMIT_HASH=$(git rev-parse --short=7 ${{ github.event.pull_request.head.sha }})" >> $GITHUB_ENV

    - name: Calculate commit hash for merge commit
      if: github.event_name != 'pull_request'
      run: echo "COMMIT_HASH=$(git rev-parse --short=7 HEAD)" >> $GITHUB_ENV

    - name: Build
      run: |
        rm -f ./MM_VERSION
        echo $COMMIT_HASH > ./MM_VERSION
        cargo build --bin mm2 --profile ci --target x86_64-apple-darwin

    - name: Compress build output
      run: |
        NAME="mm2_$COMMIT_HASH-mac-x86-64.zip"
        zip $NAME target/x86_64-apple-darwin/ci/mm2 -j
        mkdir $BRANCH_NAME
        mv $NAME ./$BRANCH_NAME/

    - name: Upload output
      uses: garygrossgarten/github-action-scp@release
      with:
        host: ${{ secrets.FILE_SERVER_HOST }}
        username: ${{ secrets.FILE_SERVER_USERNAME }}
        port: ${{ secrets.FILE_SERVER_PORT }}
        privateKey: ${{ secrets.FILE_SERVER_KEY }}
        local: ${{ env.BRANCH_NAME }}
        remote: "/uploads/${{ env.BRANCH_NAME }}"

  win-x86-64:
    timeout-minutes: 30
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install toolchain
      run: |
        rustup toolchain install nightly-2022-10-29 --no-self-update --profile=minimal
        rustup default nightly-2022-10-29

    - name: Calculate commit hash for PR commit
      if: github.event_name == 'pull_request'
      run: echo "COMMIT_HASH=$(git rev-parse --short=7 ${{ github.event.pull_request.head.sha }})" >> $Env:GITHUB_ENV

    - name: Calculate commit hash for merge commit
      if: github.event_name != 'pull_request'
      run: echo "COMMIT_HASH=$(git rev-parse --short=7 HEAD)" >> $Env:GITHUB_ENV

    - name: Build
      run: |
        if (test-path "./MM_VERSION") {
          remove-item "./MM_VERSION"
        }
        echo $Env:COMMIT_HASH > ./MM_VERSION
        cargo build --bin mm2 --profile ci

    - name: Compress build output
      run: |
        $NAME="mm2_$Env:COMMIT_HASH-win-x86-64.zip"
        7z a $NAME .\target\ci\mm2.exe .\target\ci\*.dll
        mkdir $Env:BRANCH_NAME
        mv $NAME ./$Env:BRANCH_NAME/

    - name: Upload output
      uses: garygrossgarten/github-action-scp@release
      with:
        host: ${{ secrets.FILE_SERVER_HOST }}
        username: ${{ secrets.FILE_SERVER_USERNAME }}
        port: ${{ secrets.FILE_SERVER_PORT }}
        privateKey: ${{ secrets.FILE_SERVER_KEY }}
        local: ${{ env.BRANCH_NAME }}
        remote: "/uploads/${{ env.BRANCH_NAME }}"

  mac-dylib-x86-64:
    timeout-minutes: 30
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install toolchain
      run: |
        rustup toolchain install nightly-2022-10-29 --no-self-update --profile=minimal
        rustup default nightly-2022-10-29

    - name: Calculate commit hash for PR commit
      if: github.event_name == 'pull_request'
      run: echo "COMMIT_HASH=$(git rev-parse --short=7 ${{ github.event.pull_request.head.sha }})" >> $GITHUB_ENV

    - name: Calculate commit hash for merge commit
      if: github.event_name != 'pull_request'
      run: echo "COMMIT_HASH=$(git rev-parse --short=7 HEAD)" >> $GITHUB_ENV

    - name: Build
      run: |
        rm -f ./MM_VERSION
        echo $COMMIT_HASH > ./MM_VERSION
        cargo rustc --target x86_64-apple-darwin --lib --profile ci --package mm2_bin_lib --crate-type=staticlib

    - name: Compress build output
      run: |
        NAME="mm2_$COMMIT_HASH-mac-dylib-x86-64.zip"
        mv target/x86_64-apple-darwin/ci/libmm2lib.a target/x86_64-apple-darwin/ci/libmm2.a
        zip $NAME target/x86_64-apple-darwin/ci/libmm2.a -j
        mkdir $BRANCH_NAME
        mv $NAME ./$BRANCH_NAME/

    - name: Upload output
      uses: garygrossgarten/github-action-scp@release
      with:
        host: ${{ secrets.FILE_SERVER_HOST }}
        username: ${{ secrets.FILE_SERVER_USERNAME }}
        port: ${{ secrets.FILE_SERVER_PORT }}
        privateKey: ${{ secrets.FILE_SERVER_KEY }}
        local: ${{ env.BRANCH_NAME }}
        remote: "/uploads/${{ env.BRANCH_NAME }}"

  wasm:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install toolchain
      run: |
        rustup toolchain install nightly-2022-10-29 --no-self-update --profile=minimal
        rustup default nightly-2022-10-29
        rustup target add wasm32-unknown-unknown

    - name: Install wasm-pack
      run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

    - name: Calculate commit hash for PR commit
      if: github.event_name == 'pull_request'
      run: echo "COMMIT_HASH=$(git rev-parse --short=7 ${{ github.event.pull_request.head.sha }})" >> $GITHUB_ENV

    - name: Calculate commit hash for merge commit
      if: github.event_name != 'pull_request'
      run: echo "COMMIT_HASH=$(git rev-parse --short=7 HEAD)" >> $GITHUB_ENV

    - name: Build
      run: |
        rm -f ./MM_VERSION
        echo $COMMIT_HASH > ./MM_VERSION
        wasm-pack build mm2src/mm2_bin_lib --target web --out-dir ../../target/target-wasm-release

    - name: Compress build output
      run: |
        NAME="mm2_$COMMIT_HASH-wasm.zip"
        zip $NAME ./target/target-wasm-release/mm2lib_bg.wasm ./target/target-wasm-release/mm2lib.js ./target/target-wasm-release/snippets -j
        mkdir $BRANCH_NAME
        mv $NAME ./$BRANCH_NAME/

    - name: Upload output
      uses: garygrossgarten/github-action-scp@release
      with:
        host: ${{ secrets.FILE_SERVER_HOST }}
        username: ${{ secrets.FILE_SERVER_USERNAME }}
        port: ${{ secrets.FILE_SERVER_PORT }}
        privateKey: ${{ secrets.FILE_SERVER_KEY }}
        local: ${{ env.BRANCH_NAME }}
        remote: "/uploads/${{ env.BRANCH_NAME }}"

  ios-aarch64:
    timeout-minutes: 30
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install toolchain
      run: |
        rustup toolchain install nightly-2022-10-29 --no-self-update --profile=minimal
        rustup default nightly-2022-10-29
        rustup target add aarch64-apple-ios

    - name: Calculate commit hash for PR commit
      if: github.event_name == 'pull_request'
      run: echo "COMMIT_HASH=$(git rev-parse --short=7 ${{ github.event.pull_request.head.sha }})" >> $GITHUB_ENV

    - name: Calculate commit hash for merge commit
      if: github.event_name != 'pull_request'
      run: echo "COMMIT_HASH=$(git rev-parse --short=7 HEAD)" >> $GITHUB_ENV

    - name: Build
      run: |
        rm -f ./MM_VERSION
        echo $COMMIT_HASH > ./MM_VERSION
        cargo rustc --target aarch64-apple-ios --lib --profile ci --package mm2_bin_lib --crate-type=staticlib

    - name: Compress build output
      run: |
        NAME="mm2_$COMMIT_HASH-ios-aarch64.zip"
        mv target/aarch64-apple-ios/ci/libmm2lib.a target/aarch64-apple-ios/ci/libmm2.a
        zip $NAME target/aarch64-apple-ios/ci/libmm2.a -j
        mkdir $BRANCH_NAME
        mv $NAME ./$BRANCH_NAME/

    - name: Upload output
      uses: garygrossgarten/github-action-scp@release
      with:
        host: ${{ secrets.FILE_SERVER_HOST }}
        username: ${{ secrets.FILE_SERVER_USERNAME }}
        port: ${{ secrets.FILE_SERVER_PORT }}
        privateKey: ${{ secrets.FILE_SERVER_KEY }}
        local: ${{ env.BRANCH_NAME }}
        remote: "/uploads/${{ env.BRANCH_NAME }}"

  android-aarch64:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install toolchain
      run: |
        rustup toolchain install nightly-2022-10-29 --no-self-update --profile=minimal
        rustup default nightly-2022-10-29
        rustup target add aarch64-linux-android

    - name: Setup NDK
      run: ./android-ndk.sh x86 21

    - name: Calculate commit hash for PR commit
      if: github.event_name == 'pull_request'
      run: echo "COMMIT_HASH=$(git rev-parse --short=7 ${{ github.event.pull_request.head.sha }})" >> $GITHUB_ENV

    - name: Calculate commit hash for merge commit
      if: github.event_name != 'pull_request'
      run: echo "COMMIT_HASH=$(git rev-parse --short=7 HEAD)" >> $GITHUB_ENV

    - name: Build
      run: |
        rm -f ./MM_VERSION
        echo $COMMIT_HASH > ./MM_VERSION

        export PATH=$PATH:/android-ndk/bin
        CC_aarch64_linux_android=aarch64-linux-android21-clang CARGO_TARGET_AARCH64_LINUX_ANDROID_LINKER=aarch64-linux-android21-clang cargo rustc --target=aarch64-linux-android --lib --profile ci --crate-type=staticlib --package mm2_bin_lib

    - name: Compress build output
      run: |
        NAME="mm2_$COMMIT_HASH-android-aarch64.zip"
        mv target/aarch64-linux-android/ci/libmm2lib.a target/aarch64-linux-android/ci/libmm2.a
        zip $NAME target/aarch64-linux-android/ci/libmm2.a  -j
        mkdir $BRANCH_NAME
        mv $NAME ./$BRANCH_NAME/

    - name: Upload output
      uses: garygrossgarten/github-action-scp@release
      with:
        host: ${{ secrets.FILE_SERVER_HOST }}
        username: ${{ secrets.FILE_SERVER_USERNAME }}
        port: ${{ secrets.FILE_SERVER_PORT }}
        privateKey: ${{ secrets.FILE_SERVER_KEY }}
        local: ${{ env.BRANCH_NAME }}
        remote: "/uploads/${{ env.BRANCH_NAME }}"

  android-armv7:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install toolchain
      run: |
        rustup toolchain install nightly-2022-10-29 --no-self-update --profile=minimal
        rustup default nightly-2022-10-29
        rustup target add armv7-linux-androideabi

    - name: Setup NDK
      run: ./android-ndk.sh x86 21

    - name: Calculate commit hash for PR commit
      if: github.event_name == 'pull_request'
      run: echo "COMMIT_HASH=$(git rev-parse --short=7 ${{ github.event.pull_request.head.sha }})" >> $GITHUB_ENV

    - name: Calculate commit hash for merge commit
      if: github.event_name != 'pull_request'
      run: echo "COMMIT_HASH=$(git rev-parse --short=7 HEAD)" >> $GITHUB_ENV

    - name: Build
      run: |
        rm -f ./MM_VERSION
        echo $COMMIT_HASH > ./MM_VERSION

        export PATH=$PATH:/android-ndk/bin
        CC_armv7_linux_androideabi=armv7a-linux-androideabi21-clang CARGO_TARGET_ARMV7_LINUX_ANDROIDEABI_LINKER=armv7a-linux-androideabi21-clang cargo rustc --target=armv7-linux-androideabi --lib --profile ci --crate-type=staticlib --package mm2_bin_lib

    - name: Compress build output
      run: |
        NAME="mm2_$COMMIT_HASH-android-armv7.zip"
        mv target/armv7-linux-androideabi/ci/libmm2lib.a target/armv7-linux-androideabi/ci/libmm2.a
        zip $NAME target/armv7-linux-androideabi/ci/libmm2.a   -j
        mkdir $BRANCH_NAME
        mv $NAME ./$BRANCH_NAME/

    - name: Upload output
      uses: garygrossgarten/github-action-scp@release
      with:
        host: ${{ secrets.FILE_SERVER_HOST }}
        username: ${{ secrets.FILE_SERVER_USERNAME }}
        port: ${{ secrets.FILE_SERVER_PORT }}
        privateKey: ${{ secrets.FILE_SERVER_KEY }}
        local: ${{ env.BRANCH_NAME }}
        remote: "/uploads/${{ env.BRANCH_NAME }}"


  deployment-commitment:
    if: github.event_name != 'pull_request'
    needs: linux-x86-64
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Calculate commit hash for PR commit
        if: github.event_name == 'pull_request'
        run: echo "COMMIT_HASH=$(git rev-parse --short=7 ${{ github.event.pull_request.head.sha }})" >> $GITHUB_ENV

      - name: Calculate commit hash for merge commit
        if: github.event_name != 'pull_request'
        run: echo "COMMIT_HASH=$(git rev-parse --short=7 HEAD)" >> $GITHUB_ENV

      - name: Activate SSH
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.ATOMICDEX_DEPLOYMENTS_SSH }}

      - name: Commitment
        run: |
          git clone git@github.com:KomodoPlatform/atomicdex-deployments.git
          if [ -d "atomicdex-deployments/atomicDEX-API" ]; then
            cd atomicdex-deployments/atomicDEX-API
            sed -i "1s/^.*$/$COMMIT_HASH/" .commit
            git config --global user.email "linuxci@komodoplatform.com"
            git config --global user.name "linuxci"
            git add .commit
            git commit -m "[atomicDEX-API] $COMMIT_HASH is committed for git & container registry"
            git push
          fi
