name: Format and Lint
on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  fmt-and-lint:
    timeout-minutes: 45
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
    - uses: actions/checkout@v3
    - name: Install toolchain
      run: |
        rustup toolchain install nightly-2022-10-29 --no-self-update --profile=minimal --component rustfmt clippy
        rustup default nightly-2022-10-29

    - name: fmt check
      run: cargo fmt -- --check

    - name: x86-64 code lint
      run: cargo clippy --all-targets --profile ci -- --D warnings

  wasm-lint:
    timeout-minutes: 45
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install toolchain
      run: |
        rustup toolchain install nightly-2022-10-29 --no-self-update --profile=minimal --component clippy
        rustup default nightly-2022-10-29
        rustup target add wasm32-unknown-unknown

    - name: wasm code lint
      run: cargo clippy --target wasm32-unknown-unknown --profile ci -- --D warnings
