name: PR Lint

on:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize
      - labeled
      - unlabeled

jobs:
  main:
    name: Validate PR
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v5.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          types: |
            feat
            fix
            improvement
            chore
            docs
            deps
            test
            refactor
            ci
          requireScope: true
          # Do not allow starting with uppercase for subject part
          subjectPattern: ^(?![A-Z]).+$
          headerPatternCorrespondence: type, scope, subject

      - name: Check PR title length
        env:
          TITLE: ${{ github.event.pull_request.title }}
        run: |
          title_length=${#TITLE}
          if [ $title_length -gt 85 ]
          then
            echo "PR title is too long (greater than 85 characters)"
            exit 1
          fi

      - name: Check PR labels
        env:
          LABEL_NAMES: ${{ toJson(github.event.pull_request.labels.*.name) }}
        if: contains(env.LABEL_NAMES, 'under review') == contains(env.LABEL_NAMES, 'in progress')
        run: |
          # Filter labels starting with "status:"
          STATUS_LABELS=$(echo $LABEL_NAMES | jq -r '.[] | select(startswith("status:"))')
          STATUS_COUNT=$(echo "$STATUS_LABELS" | wc -l)
          
          echo "Found status labels: $STATUS_LABELS"
          echo "Count of status labels: $STATUS_COUNT"
          
          if [ "$STATUS_COUNT" -ne 1 ]
          then
            echo "PR must have exactly one label starting with 'status:'. Found $STATUS_COUNT."
            exit 1
          fi
